
# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Маслаков Владислав Денисович",
  "bithDate": "17.09.2003",
  "password": "Tinivini20",
  "phone": "89068006808",
  "mail": "maslakov20@mail.ru",
  "balance": 1000,
  "subscribe": false,
  "subscribeEnd": "04.01",
  "notification": [""]
}

###

## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "mail": "maslakov20@mail.ru",
  "password": "Tinivini20"
}

###

## Получение всех польхователей

GET http://localhost:4000/users/ HTTP/1.1
Content-Type: application/json

###

## Получение пользователя

GET http://localhost:4000/users/login/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJtYWlsIjoibWFzbGFrb3YyMEBtYWlsLnJ1IiwiaWQiOiI2ODBlNTE4YmQ2NTg5MDUxZWMwN2I3YjQiLCJpYXQiOjE3NDU5MzU0ODcsImV4cCI6MTc0NjEwODI4N30.6gbHfCNh4HNn5Wz4J5HYyv3DRKfxn-hkJgH5cM6ONjA
Content-Type: application/json

###
